site_name: OpenAI Agents SDK
theme:
    name: material
    features:
        # Allows copying code blocks
        - content.code.copy
        # Allows selecting code blocks
        - content.code.select
        # Shows the current path in the sidebar
        - navigation.path
        # Shows sections in the sidebar
        - navigation.sections
        # Shows sections expanded by default
        - navigation.expand
        # Enables annotations in code blocks
        - content.code.annotate
    palette:
        primary: black
    logo: logo/light.svg
    # favicon: images/favicon-platform.svg
nav:
    - 新手入门
        - introduction.mdx
        - 快速开始
            - quickstart/server.mdx
            - quickstart/client.mdx
            - quickstart/user.mdx
        - examples.mdx
        - clients.mdx
    - 指引
        - tutorials/building-mcp-with-llms.mdx
        - docs/tools/debugging.mdx
        - docs/tools/inspector.mdx
    - 概念
        - docs/concepts/architecture.mdx
        - docs/concepts/resources.mdx
        - docs/concepts/prompts.mdx
        - docs/concepts/tools.mdx
        - docs/concepts/sampling.mdx
        - docs/concepts/roots.mdx
        - docs/concepts/transports.mdx
    - 开发
        - development/updates.mdx
        - development/roadmap.mdx
        - development/contributing.mdx

plugins:
    - search
    # - mkdocstrings:
    #       handlers:
    #           python:
    #               paths: ["src/agents"]
    #               selection:
    #                   docstring_style: google
    #               options:
    #                   # Shows links to other members in signatures
    #                   signature_crossrefs: true
    #                   # Orders members by source order, rather than alphabetical
    #                   members_order: source
    #                   # Puts the signature on a separate line from the member name
    #                   separate_signature: true
    #                   # Shows type annotations in signatures
    #                   show_signature_annotations: true
    #                   # Makes the font sizes nicer
    #                   heading_level: 3

extra:
    # Remove material generation message in footer
    generator: false

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

validation:
    omitted_files: warn
    absolute_links: warn
    unrecognized_links: warn
    anchors: warn

extra_css:
    - stylesheets/extra.css

# watch:
#     - "src/agents"
